name: Trigger Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Ping test repo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Omkar-dalvi-qa/Dubai-Opera-TestCases/dispatches \
            -d '{"event_type":"dev-push"}'